apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
        - name: python-app
          image: tyagibhavya/python-sample-app-demo:v1
          #env:
          #- name: DB-PORT
            #valueFrom:
              #configMapKeyRef:
                 #name: test-cm
                 #key: db-port
          volumeMounts:
            - name: db-connection
              mountPath: /opt
          ports:
          - containerPort: 8000
      volumes:  #creating volume
       - name: db-connection
         configMap:
           name: test-cm
